In [1]:
import numpy as np

In [4]:
arr1 = np.array([30,40,60,20,10])
arr2 = np.array([30,20,10,20,20])
print(arr1 + arr2) # It adds value of arr1 in arr2 like 30+40 and 40+20

[60 60 70 40 30]


In [5]:
print(np.add(arr1,arr2)) # Same as print(arr1 + arr2)

[60 60 70 40 30]


In [8]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1 + arr2)

[[60 60]
 [40 30]]


In [10]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1 - arr2)

[[  0  20]
 [  0 -10]]


In [12]:
print(np.subtract(arr1,arr2)) # Same as print(arr1 - arr2)

[[  0  20]
 [  0 -10]]


In [14]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1 * arr2)

[[900 800]
 [400 200]]


In [15]:
print(np.multiply(arr1,arr2)) # Same as print(arr1 * arr2)

[[900 800]
 [400 200]]


In [16]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1 / arr2)

[[1.  2. ]
 [1.  0.5]]


In [17]:
print(np.divide(arr1,arr2)) # Same as print(arr1 / arr2)

[[1.  2. ]
 [1.  0.5]]


In [26]:
arr1 = np.array([3,4,2,10])
arr2 = np.array([2])
print(np.power(arr1,arr2)) # It prints power in 3 of all elements of arr1

[  9  16   4 100]


In [28]:
arr1 = np.array([9,16,4,100])
print(np.sqrt(arr1)) # Find square root
print(arr1.dtype)

[ 3.  4.  2. 10.]
