In [1]:
a = [30,40,50]
b = [5,5,3]
print(a+b) # add 2 list

[30, 40, 50, 5, 5, 3]


In [3]:
import numpy as np

# Concatenate
arr1 = np.array([30,40,50])
arr2 = np.array([5,5,3])
print(np.concatenate([arr1,arr2]))

[30 40 50  5  5  3]


In [5]:
print(np.concatenate([arr1,arr2],axis=0)) # same output as becasue 1 dimension

[30 40 50  5  5  3]


In [6]:
arr1 = np.array([[30,40],[50,10]])
arr2 = np.array([[5,5],[3,3]])
print(np.concatenate([arr1,arr2]))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [8]:
print(np.concatenate([arr1,arr2],axis=0))
print(np.concatenate([arr1,arr2],axis=1)) # Now there is 2 dimension arrays so output will change

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]
[[30 40  5  5]
 [50 10  3  3]]


In [10]:
print(np.hstack([arr1,arr2])) # Horizontal Concatenation

[[30 40  5  5]
 [50 10  3  3]]


In [12]:
print(np.vstack([arr1,arr2])) # Vertical Concatenation

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [13]:
#Split

a = np.array([20,40,30,40,10,20])
print(np.array_split(a,3)) # It splits the array in 3 arrays

[array([20, 40]), array([30, 40]), array([10, 20])]


In [17]:
a = np.array([20,40,30,40,10,20])
b = (np.array_split(a,3))
print(b[1]) # It prints array 1 as index is given

[30 40]


In [20]:
a = np.array([20,40,30,40,10,20])
b = (np.array_split(a,4))
print(b)

[array([20, 40]), array([30, 40]), array([10]), array([20])]


In [22]:
a = np.array([20,40,30,40,10,20])
b = (np.array_split(a,5))
print(b)

[array([20, 40]), array([30]), array([40]), array([10]), array([20])]


In [23]:
a = np.array([[20,40],[30,40],[10,20]])
b = (np.array_split(a,4))
print(b)

[array([[20, 40]]), array([[30, 40]]), array([[10, 20]]), array([], shape=(0, 2), dtype=int64)]
