In [1]:
import numpy as np

a = np.array([20,40,60,80])
print(np.append(a,90))

[20 40 60 80 90]


In [3]:
a = np.array([[20,40],[60,80]])
print(np.append(a,[90,100])) # It gets converted in 1 dimension then append new element

[ 20  40  60  80  90 100]


In [4]:
a = np.array([20,40,60,80])
print(np.insert(a,1,50)) # Insert element in required index (array,index,value)

[20 50 40 60 80]


In [7]:
a = np.array([[20,40],[60,80]])
print(np.insert(a,1,50))

[20 50 40 60 80]


In [9]:
a = np.array([[20,40],[60,80]])
print(np.insert(a,1,[50,60], axis = 0))

[[20 40]
 [50 60]
 [60 80]]


In [10]:
a = np.array([[20,40],[60,80]])
print(np.insert(a,1,[50,60], axis = 1))

[[20 50 40]
 [60 60 80]]


In [12]:
a = np.array([[20,40],[60,80]])
print(np.insert(a,1,[50], axis = 0)) # print 50 two times because it is in matrix form

[[20 40]
 [50 50]
 [60 80]]


In [14]:
a = np.array([[20,40],[60,80]])
print(np.insert(a,[1,2],[50], axis = 0))

[[20 40]
 [50 50]
 [60 80]
 [50 50]]


In [17]:
a = np.array([[20,40],[60,80]])
print(np.delete(a,1)) # First it converts in 1D then index 1 element deleted

[20 60 80]


In [20]:
a = np.array([[20,40],[60,80]])
print(a)
print(np.delete(a,1, axis = 0)) # Delete row in index 1

[[20 40]
 [60 80]]
[[20 40]]


In [22]:
a = np.array([[20,40],[60,80]])
print(a)
print(np.delete(a,1, axis = 1)) # Delete column in index 1

[[20 40]
 [60 80]]
[[20]
 [60]]
