In [2]:
import numpy as np

ar = np.array([3,4,1,7,8])
s = np.where(ar == 4)
print(s)

(array([1]),)


In [4]:
s = np.where(ar == 7)
print(s)

(array([3]),)


In [6]:
s = np.where(ar % 2 == 0)
print(s)

(array([1, 4]),)


In [ ]:
ar = np.array([3,4,1,7,8])
ss = np.searchsorted(ar, )